# Writes lib/l10n/app_{en,de,tr}.arb from one table so the three stay in step.
# Run: python3 tool/gen_arb.py
import json, os
S = 'String'
I = 'int'
T = [
 ('appTitle', 'Bayramlaşma', 'Bayramlaşma', 'Bayramlaşma', {}),
 ('tabCalls', 'Calls', 'Anrufe', 'Aramalar', {}),
 ('tabPeople', 'People', 'Personen', 'Kişiler', {}),
 ('kindRamazan', 'Ramazan Bayramı', 'Ramazan Bayramı', 'Ramazan Bayramı', {}),
 ('kindKurban', 'Kurban Bayramı', 'Kurban Bayramı', 'Kurban Bayramı', {}),
 ('kindNewYear', 'New Year', 'Neujahr', 'Yılbaşı', {}),
 ('kindMothersDay', "Mother's Day", 'Muttertag', 'Anneler Günü', {}),
 ('kindFathersDayTr', "Father's Day in Turkey", 'Vatertag in der Türkei', 'Babalar Günü', {}),
 ('kindVatertag', "Father's Day in Germany", 'Vatertag', 'Almanya Babalar Günü', {}),
 ('kindBirthday', 'Birthday', 'Geburtstag', 'Doğum günü', {}),
 ('birthdayOf', "{name}'s Birthday", 'Geburtstag von {name}', 'Doğum günü: {name}', {'name': S}),
 ('occasionYear', '{occasion} {year}', '{occasion} {year}', '{occasion} {year}', {'occasion': S, 'year': S}),
 ('kindMothersDayNote', 'Second Sunday of May, in Turkey and in Germany', 'Zweiter Sonntag im Mai, in der Türkei und in Deutschland', 'Mayıs ayının ikinci pazarı, Türkiye ve Almanya', {}),
 ('kindFathersDayTrNote', 'Third Sunday of June', 'Dritter Sonntag im Juni', 'Haziran ayının üçüncü pazarı', {}),
 ('kindVatertagNote', 'Ascension Day', 'Christi Himmelfahrt', 'Hristiyanların Göğe Yükseliş günü', {}),
 ('circleElders', 'Elders', 'Ältere', 'Büyükler', {}),
 ('circleFamily', 'Family', 'Familie', 'Aile', {}),
 ('circleFriends', 'Friends', 'Freunde', 'Arkadaşlar', {}),
 ('hijriShawwal', '{day} Shawwal {year}', '{day}. Schawwal {year}', '{day} Şevval {year}', {'day': I, 'year': I}),
 ('hijriDhuAlHijjah', '{day} Dhu al-Hijjah {year}', '{day}. Dhu l-Hiddscha {year}', '{day} Zilhicce {year}', {'day': I, 'year': I}),
 ('startsTomorrow', 'Starts tomorrow', 'Beginnt morgen', 'Yarın', {}),
 ('arefeToday', 'Arefe today, starts tomorrow', 'Heute Arefe, morgen geht es los', 'Bugün arefe, bayram yarın', {}),
 ('dayOf', 'Day {day} of {total}', 'Tag {day} von {total}', 'Bayramın {day}. günü', {'day': I, 'total': I}),
 ('today', 'Today', 'Heute', 'Bugün', {}),
 ('endedYesterday', 'Ended yesterday', 'Gestern zu Ende gegangen', 'Dün bitti', {}),
 ('inDays', 'In {count, plural, =1{1 day} other{{count} days}}', 'In {count, plural, =1{1 Tag} other{{count} Tagen}}', '{count} gün sonra', {'count': I}),
 ('reachedOf', '{done} of {total} reached', '{done} von {total} erreicht', '{total} kişiden {done} kişiye ulaşıldı', {'done': I, 'total': I}),
 ('peopleCount', '{count, plural, =1{1 person} other{{count} people}}', '{count, plural, =1{1 Person} other{{count} Personen}}', '{count} kişi', {'count': I}),
 ('leftCount', '{count} left', 'Noch {count}', '{count} kişi kaldı', {'count': I}),
 ('sectionNow', 'Now', 'Jetzt', 'Şimdi', {}),
 ('sectionUpcoming', 'Coming Up', 'Demnächst', 'Yaklaşanlar', {}),
 ('sectionEarlier', 'Earlier', 'Frühere Runden', 'Geçmiş', {}),
 ('datesFooter', "Bayram dates follow Diyanet's calendar and are included through {year}.", 'Die Bayram-Daten folgen dem Kalender der Diyanet und sind bis {year} enthalten.', 'Bayram tarihleri Diyanet takvimine göredir, {year} yılı sonuna kadar uygulamada var.', {'year': S}),
 ('noUpcoming', 'Nothing else in the next twelve months.', 'In den nächsten zwölf Monaten steht nichts weiter an.', 'Önümüzdeki on iki ayda başka gün yok.', {}),
 ('emptyCallsTitle', 'Who Do You Call First?', 'Wen rufst du zuerst an?', 'İlk Kimi Ararsın?', {}),
 ('emptyCallsBody', 'Add the people you call on Bayram, elders first. Next up: {occasion}, {date}.', 'Füge die Menschen hinzu, die du zum Bayram anrufst, die Älteren zuerst. Als Nächstes: {occasion}, {date}.', 'Bayramda aradığın kişileri ekle, önce büyükleri. Sıradaki: {occasion}, {date}.', {'occasion': S, 'date': S}),
 ('addPerson', 'Add Person', 'Person hinzufügen', 'Kişi Ekle', {}),
 ('sectionReached', 'Reached', 'Erreicht', 'Ulaşılanlar', {}),
 ('allReached', 'Everyone is reached.', 'Alle sind erreicht.', 'Herkese ulaşıldı.', {}),
 ('opensOn', 'You can tick people off from {date}.', 'Ab {date} kannst du abhaken.', '{date} tarihinden itibaren işaretleyebilirsin.', {'date': S}),
 ('nobodyInRound', 'Nobody is in this round any more.', 'In dieser Runde ist niemand mehr.', 'Bu listede artık kimse yok.', {}),
 ('timeIn', '{time} in {city}', '{time} in {city}', '{city} saatiyle {time}', {'time': S, 'city': S}),
 ('nightThere', 'Night there', 'Dort ist Nacht', 'Orada gece', {}),
 ('pickCalled', 'Called', 'Angerufen', 'Aradım', {}),
 ('pickMessaged', 'Messaged', 'Geschrieben', 'Mesaj Attım', {}),
 ('pickVisited', 'Visited', 'Besucht', 'Ziyaret Ettim', {}),
 ('statusCalled', 'Called {when}', 'Angerufen {when}', 'Arandı, {when}', {'when': S}),
 ('statusMessaged', 'Messaged {when}', 'Geschrieben {when}', 'Mesaj atıldı, {when}', {'when': S}),
 ('statusVisited', 'Visited {when}', 'Besucht {when}', 'Ziyaret edildi, {when}', {'when': S}),
 ('markNotReached', 'Mark as Not Reached', 'Als nicht erreicht markieren', 'Ulaşılmadı Olarak İşaretle', {}),
 ('addNote', 'Add Note', 'Notiz hinzufügen', 'Not Ekle', {}),
 ('editNote', 'Edit Note', 'Notiz bearbeiten', 'Notu Düzenle', {}),
 ('noteHint', 'Asked about exams', 'Nach den Prüfungen gefragt', 'Sınavları sordu', {}),
 ('showNumber', 'Show Number', 'Nummer zeigen', 'Numarayı Göster', {}),
 ('copyNumber', 'Copy Number', 'Nummer kopieren', 'Numarayı Kopyala', {}),
 ('copied', 'Copied', 'Kopiert', 'Kopyalandı', {}),
 ('numberHelp', 'Call from the Phone app or your messenger.', 'Ruf über die Telefon-App oder deinen Messenger an.', 'Telefon uygulamasından ya da mesajlaşma uygulamandan ara.', {}),
 ('markCalledFor', 'Mark {name} as called', '{name} als angerufen markieren', '{name} arandı olarak işaretle', {'name': S}),
 ('unmarkFor', 'Mark {name} as not reached', '{name} als nicht erreicht markieren', '{name} ulaşılmadı olarak işaretle', {'name': S}),
 ('reorder', 'Order', 'Reihenfolge', 'Sırala', {}),
 ('reorderTitle', 'Order', 'Reihenfolge', 'Sıralama', {}),
 ('reorderFooter', 'Drag to choose who comes first. Every round follows this order.', 'Ziehen, um festzulegen, wer zuerst kommt. Jede Runde folgt dieser Reihenfolge.', 'Kimin önce geleceğini sürükleyerek seç. Her liste bu sırayı izler.', {}),
 ('dragToReorder', 'Drag to reorder {name}', '{name} verschieben', '{name} kişisini taşı', {'name': S}),
 ('eldersFooter', 'Elders come first in every round.', 'Die Älteren stehen in jeder Runde oben.', 'Büyükler her listede en üstte.', {}),
 ('emptyPeopleTitle', 'No People Yet', 'Noch niemand', 'Henüz Kimse Yok', {}),
 ('emptyPeopleBody', 'Start with the elders you call first on Bayram morning.', 'Beginne mit den Älteren, die du am Bayram-Morgen zuerst anrufst.', 'Bayram sabahı ilk aradığın büyüklerle başla.', {}),
 ('newPerson', 'New Person', 'Neue Person', 'Yeni Kişi', {}),
 ('editPerson', 'Edit Person', 'Person bearbeiten', 'Kişiyi Düzenle', {}),
 ('edit', 'Edit', 'Bearbeiten', 'Düzenle', {}),
 ('name', 'Name', 'Name', 'İsim', {}),
 ('nameHint', 'Name, like Hasan Amca', 'Name, etwa Hasan Amca', 'İsim, örneğin Hasan Amca', {}),
 ('relation', 'Relation', 'Beziehung', 'Yakınlık', {}),
 ('relationHint', 'Relation, like uncle (optional)', 'Beziehung, etwa Onkel (optional)', 'Yakınlık, örneğin amca (isteğe bağlı)', {}),
 ('phone', 'Phone', 'Telefon', 'Telefon', {}),
 ('phoneHint', 'Phone number (optional)', 'Telefonnummer (optional)', 'Telefon numarası (isteğe bağlı)', {}),
 ('circle', 'Circle', 'Gruppe', 'Grup', {}),
 ('city', 'City', 'Ort', 'Şehir', {}),
 ('birthday', 'Birthday', 'Geburtstag', 'Doğum Günü', {}),
 ('noneSet', 'None', 'Keiner', 'Yok', {}),
 ('removeBirthday', 'Remove Birthday', 'Geburtstag entfernen', 'Doğum Gününü Kaldır', {}),
 ('callOn', 'Call On', 'Anrufen an', 'Aranacak Günler', {}),
 ('callOnFooter', 'Their birthday is added when you set one.', 'Der Geburtstag kommt dazu, sobald du ihn einträgst.', 'Doğum günü girersen o gün de eklenir.', {}),
 ('deletePerson', 'Delete Person', 'Person löschen', 'Kişiyi Sil', {}),
 ('deletePersonMessage', 'Delete {name}? Their ticks in past rounds are deleted too.', '{name} löschen? Die Häkchen in früheren Runden werden auch gelöscht.', '{name} silinsin mi? Geçmiş listelerdeki işaretleri de silinir.', {'name': S}),
 ('delete', 'Delete', 'Löschen', 'Sil', {}),
 ('searchCities', 'Search', 'Suchen', 'Ara', {}),
 ('regionTurkey', 'Turkey', 'Türkei', 'Türkiye', {}),
 ('regionGermany', 'Germany', 'Deutschland', 'Almanya', {}),
 ('regionElsewhere', 'Elsewhere', 'Andere Orte', 'Diğer Yerler', {}),
 ('anyTown', 'Any other town', 'Jeder andere Ort', 'Başka bir şehir', {}),
 ('cityFooter', 'Turkey and Germany each have one time zone, so the country is enough.', 'Die Türkei und Deutschland haben je eine Zeitzone, das Land genügt also.', 'Türkiye ve Almanya tek saat diliminde, ülkeyi seçmek yeter.', {}),
 ('noCityFound', 'No city found. Pick the country or a city nearby with the same time.', 'Kein Ort gefunden. Wähle das Land oder einen Ort in der Nähe mit derselben Uhrzeit.', 'Şehir bulunamadı. Ülkeyi ya da aynı saatteki yakın bir şehri seç.', {}),
 ('cancel', 'Cancel', 'Abbrechen', 'Vazgeç', {}),
 ('save', 'Save', 'Sichern', 'Kaydet', {}),
 ('done', 'Done', 'Fertig', 'Bitti', {}),
 ('ok', 'OK', 'OK', 'Tamam', {}),
 ('discardChanges', 'Discard Changes', 'Änderungen verwerfen', 'Değişiklikleri At', {}),
 ('keepEditing', 'Keep Editing', 'Weiter bearbeiten', 'Düzenlemeye Devam Et', {}),
 ('saveFailed', 'Your last change could not be saved. Free up some storage and try again.', 'Deine letzte Änderung konnte nicht gesichert werden. Gib etwas Speicher frei und versuche es erneut.', 'Son değişikliğin kaydedilemedi. Biraz yer aç ve tekrar dene.', {}),
 ('loadFailed', 'Your saved list could not be read, so a new one was started. The old file is still on this iPhone.', 'Deine gesicherte Liste konnte nicht gelesen werden, deshalb wurde eine neue begonnen. Die alte Datei ist noch auf diesem iPhone.', 'Kayıtlı listen okunamadı, bu yüzden yeni bir liste başlatıldı. Eski dosya hâlâ bu iPhone\'da.', {}),
 ('dateRange', '{from} to {to}', '{from} bis {to}', '{from} - {to}', {'from': S, 'to': S}),
 ('arefeOn', 'Arefe {date}', 'Arefe {date}', 'Arefe {date}', {'date': S}),
 ('turnsAge', 'Turns {age}', 'Wird {age}', '{age} yaşına giriyor', {'age': I}),
]
base = os.path.join(os.path.dirname(__file__), '..', 'lib', 'l10n')
for i, loc in enumerate(['en', 'de', 'tr']):
    d = {'@@locale': loc}
    for key, en, de, tr, ph in T:
        d[key] = (en, de, tr)[i]
        if loc == 'en' and ph:
            d['@' + key] = {'placeholders': {k: {'type': v} for k, v in ph.items()}}
    with open(os.path.join(base, f'app_{loc}.arb'), 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
        f.write('\n')
print(len(T), 'strings')
